os:
  #- linux # Ubuntu 16.04 is only available for Enterprise edition...
  - osx
language: cpp
sudo: required

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];    then ./build-scripts/mac.build.sh    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];  then ./build-scripts/ubuntu.build.sh ; fi 


deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - ../Qt00.macOS.dmg
    - ../Qt00.Linux-x86_64.AppImage
  skip_cleanup: true
  on:
    tags: true